name: Work Stats Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-readme:
    name: Auto updating README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master 
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKETIME_SECRET }}
